#!/bin/sh

# linux 64 arch
env GOOS=linux GOARCH=amd64 go build -o prepare-commit-msg-linux cmd/msgcommitter/msgcommitter.go

# windows 64 arch
env GOOS=windows GOARCH=amd64 go build -o prepare-commit-msg-windows cmd/msgcommitter/msgcommitter.go
